### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [absperf/asyncinotify#5]
Could you please tag the source again? Otherwise all distributions which were shipping this Python module and were using the GitHub releases need to change their description to build the packages.

Thanks

**Comment by Taywee** [comment]
Done.

This is kind of a weird split-repository situation.  Development is primarily done on GitLab, including the CI, but I mirrored to GitHub for visibility.  I guess most downstreams are pulling from the GitHub now.  I probably should set up proper repository mirroring to ensure they correctly stay in sync.

Thanks for the heads up.

**Comment by Taywee** [comment]
This should be resolved for the long term now.  The GitLab repository mirroring and CI should take care of all deployment and keepnig this mirror in sync from now on, so human error should largely be out of the equation.
